#!/usr/bin/perl

use Tk;

# --------------------------------------------------
      $DEBUG=1;
      $DETACH="";  # "", or "&" for background process
      $XOFF=0;
      $YOFF=0;
      $XSPAN;
      $YSPAN;
# --------------------------------------------------
my $xwininfo=`xwininfo -root | grep geometry`;
chomp($xwininfo);
my ($x,$geo)=split(" ",$xwininfo);
($XSPAN,$YSPAN,$XOFF,$YOFF)=split(/\+|x/,$geo);
# print "GEO:$xwininfo : <$x -- $geo> $XSPAN .. $YSPAN";
# exit;

      $XMAX=$XSPAN-0;
      $YMAX=$YSPAN-10;

sub debug {
    if ( $DEBUG )  {
	my ($t)=shift;
	print $t;
    }
}

# -------------------------------------------------
sub loadscript  {
    $cnt=0;
    my ($scr)=shift;
    open(SCR,$scr);
    while(<SCR>)  {
	chomp;
	if ( /^#/ )  {
	     debug("$_\n");
	     next;
	 }
	( $IMAGE[$cnt], $SOUND[$cnt], $TIME[$cnt], $LOC[$cnt], $BG[$cnt] )=split(/:/,$_);
	debug("{ $cnt } $IMAGE[$cnt]\t$SOUND[$cnt]\t($TIME[$cnt] sec, LOC:$LOC[$cnt], BG:$BG[$cnt])\n");
	$cnt++; 
    }  
    $ptr=-1;
}

# ------------------------------------------------
sub mpegplay  {
    system("killall mpg123");
    if ( $SOUND[$ptr] eq "-" )  { return; }
  
    system("mpg123 $SOUND[$ptr] &");
}

sub play  {
    system("killall play");
    if ( $SOUND[$ptr] eq "-" )  { return; }
  
    system("play $SOUND[$ptr] &");
}

# ------------------------------------------------
sub init  {
	$top = MainWindow->new();
	$menubar= $top->Frame()->pack;

	$menu_freerun=$menubar->
	    Button(-text => "RUN", -command => \&freerun )
		->pack(-side => left);
        # --------------------------------------
	$scale=$menubar->
	    Scale(-orient => 'horizontal',
		  -from   => -1,
		  -to     => $cnt,
		  -length => 200,
		  -variable => \$ptr,
		  -command => \&jump
		  )->pack(-side => left);
                             	$menu_next=$menubar->
	    Button(-text => "Next", -command => \&nextstep )
		->pack(-side => left);
	$menu_stop=$menubar->
	    Button(-text => "Stop", -command => \&stop, -bg => darkgrey )
		->pack(-side => left);
	$menu_step=$menubar->
	    Button(-text => "Step", -command => \&step )
		->pack(-side => left);
	$menu_exit=$menubar->
	    Button(-text => "EXIT", -command => \&exit, -bg => darkred )
		->pack(-side => left);
        # --------------------------------------

	$canvas = $top->Canvas(width=>$XMAX, height=>$YMAX)->pack();
	# loadit($IMG[0]);
	freerun();
}

# -------------------------------------------------
sub jump  {
    system("killall play");
    $ptr--;
    reset_timer;
    nextstep;
}
# -------------------------------------------------
sub nextstep  {
    $ptr++;
    if ( $ptr >= $cnt ) {
	debug("\n\n~~~~~~~~~~~~~~{ RECYCLING }~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n\n\n");
	$ptr=0;  
	$canvas->delete(all);
    }
    debug("===============================================================\n");
    debug("  { $ptr/$cnt }   $SOUND[$ptr]  $IMAGE[$ptr] ($TIME[$ptr])\n");
    debug("===============================================================\n");
    $loaded=loadimg($IMAGE[$ptr]);
    showimg($loaded);
    play($SOUND[$ptr]);
    if ( $MODE eq "freerun" ) {
	$timer=$canvas->after( $TIME[$ptr]*1000,\&nextstep);
    }
}

# ------------------------------------------------
sub reset_timer  {
    if ($MODE eq "freerun")  {
	if ( defined $timer )  {
	    $timer->cancel();
	}
    }
}

# ------------------------------------------------
sub stop {
    reset_timer;
    system("killall play");
    $MODE="stop";
}

# ------------------------------------------------
sub freerun {
   $MODE="freerun";
   nextstep;    
}

# ------------------------------------------------
sub step {
   reset_timer;
   $MODE="step";
   nextstep;    
}

# ------------------------------------------------

sub loadimg {
    my ($IMG)=shift;
    print "Loading $IMG\n";
    $image = $canvas->Photo( -file =>$IMG, -format => gif );
    return($image);
}

sub showimg {
    my ($imgobj)=shift;
    my $bg=$BG[$ptr];
    my $loc=$LOC[$ptr];
    my $xoff=$XOFF;  # reset to default
    my $yoff=$YOFF;

    if ( $loc eq "" ) { $loc=nw; }
    if ( $loc eq "c" ) { $xoff=$XMAX/2; $yoff=$YMAX/2; }
    if ( $loc eq "n" ) { $xoff=$XMAX/2; }
    if ( $loc eq "s" ) { $xoff=$XMAX/2; $yoff=$YMAX; }
    if ( $loc eq "w" ) { $yoff=$YMAX/2; }
    if ( $loc eq "e" ) { $xoff=$XMAX; $yoff=$YMAX/2; } 
   if ( $bg ne "" )  {
	$canvas->create('rectangle',0,0,$XMAX,$YMAX,-fill => $bg);
    }
    $canvas->createImage($xoff,$yoff, -anchor => $loc, -image => $imgobj);
}

sub loadit {
    my ($img)=shift;
  $cur=loadimg($img);
  showimg($cur);
} 
# ===========================================
#              MAIN
# =========================================== 
$SCR=shift(@ARGV);
loadscript($SCR);
init();
MainLoop;















